#include <regex>
#include <string>
#include <sstream>
#include <iostream>
#include <iostream>
#include <stdlib.h>
#include "./Models/Utils/MyUtils.hpp"
#include "./Models/PascalTriangle.hpp"
#include "./Models/BiNomialExpansion.hpp"